# base ubuntu image
FROM ubuntu:xenial

RUN apt-get update 

# Cutadapt
RUN apt-get install -y python3 python3-pip
RUN pip3 install cutadapt

# FastQC
RUN apt-get install -y fastqc

# trim_galore
RUN apt-get install -y curl
RUN curl -fsSL https://github.com/FelixKrueger/TrimGalore/archive/0.6.6.tar.gz -o trim_galore.tar.gz
RUN tar xvzf trim_galore.tar.gz
ENV PATH="$PATH:/TrimGalore-0.6.6"

RUN apt-get clean

WORKDIR /data